import mongoose from "mongoose";

const orderSchema = new mongoose.Schema({
  items: [
    {
      productId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: "Product",
        required: true,
      },
      productName: String,
      quantity: {
        type: Number,
        required: true,
        min: 1,
      },
      // Impact factors per unit (snapshot at purchase time)
      plasticSavedFactor: { type: Number, default: 0 },
      carbonAvoidedFactor: { type: Number, default: 0 },
      isLocallySourced: { type: Boolean, default: false },
    },
  ],
  totalAmount: {
    type: Number,
    required: true,
  },
  // AI Generated Impact Report
  impactReport: {
    plasticSavedKg: Number,
    carbonAvoidedKg: Number,
    localSourcingSummary: String,
    impactStatement: String, // The narrative generated by AI
    generatedAt: Date,
  },
  status: {
    type: String,
    default: "pending",
  },
  createdAt: {
    type: Date,
    default: Date.now,
  },
});

export default mongoose.model("Order", orderSchema);
